var mav=[
 "Abádszalók","Abaliget","Aba-Sárkeresztúr","Abaújkér","Abaújszántó"
,"Abaújszántói fürdő","Abda","Abony","Abonyi út","Abos-Sároskőszeg [Kysak]"
,"Ábrahámhegy","Ács","Acsa [Acsa-Erdőkürt]","Acsád","Acsa-Erdőkürt"
,"Adács","Ádánd","Adony","Agárd","Aggtelek [Jósvafő-Aggtelek]"
,"Ajak","Ajka","Ajka-Gyártelep","Alagimajor","Alap"
,"Alba-Iulia","Albertirsa","Alesd","Algyő","Almár"
,"Almás","Almásfüzitő","Almásfüzitő felső","Alsóbélatelep","Alsóboldva"
,"Alsógalla","Alsógöd","Alsógyenes","Alsóméntelek","Alsómocsolád [Mágocs-Alsómocsolád]"
,"Alsónána [Mórágy-Alsónána]","Alsónemesapáti","Alsónyék","Alsóörs","Alsórönök"
,"Alsószeleste [Ölbő-Alsószeleste]","Alsótengelic [Kölesd-Alsótengelic]","Alsóúrrét","Ambrózfalva","Amstetten"
,"Andocs","Andornaktálya","Andráshida","Angyalföld [Budapest-Angyalföld]","Apa"
,"Apafa","Apagy","Apátfalva","Apc-Zagyvaszántó","Aquincum felső"
,"Arad","Aradványpuszta","Aranyosapáti","Árpádszállás","Aszaló"
,"Ászár","Ászár-Keményítőgyár","Aszód","Aszófő","Áta"
,"Attala","Attnang-Puchheim","Authal","Babócsa","Bábolna [Nagyigmánd-Bábolna]"
,"Bábonymegyer","Backa Topola","Backi Vinogradi","Bácsalmás","Bácsbokod-Bácsborsód"
,"Bácsborsód [Bácsbokod-Bácsborsód]","Bad Fischau-Brunn","Bad Neusiedl am See","Bad Sauerbrunn","Bad Schandau"
,"Badacsony","Badacsonylábdihegy","Badacsonyörs","Badacsonytomaj","Badacsonytördemic-Szigliget"
,"Bag","Bagimajor","Bagod","Bágyogszovát","Baia Mare"
,"Baile Tusnad","Baja","Baja-Dunafürdő","Bajánsenye","Bak"
,"Bakonygyirót","Bakonypéterd","Bakonysárkány","Bakonyszentlászló","Baktalórántháza"
,"Baktüttös","Balassagyarmat","Balástya","Balatonakali-Dörgicse","Balatonakarattya"
,"Balatonaliga","Balatonalmádi","Balatonarács","Balatonberény","Balatonboglár"
,"Balatonederics","Balatonfenyves","Balatonfenyves alsó","Balatonfenyves GV","Balatonfőkajár felső"
,"Balatonföldvár","Balatonfüred","Balatonfűzfő","Balatongyörök","Balatonkenese"
,"Balatonkenese-Üdülőtelep","Balatonkeresztúr","Balatonlelle","Balatonlelle felső","Balatonmáriafürdő"
,"Balatonmáriafürdő alsó","Balatonrendes","Balatonszárszó","Balatonszemes","Balatonszentgyörgy"
,"Balatonszepezd","Balatonszéplak alsó","Balatonszéplak felső","Balatonudvari","Balatonújlak"
,"Balatonvilágos","Balázsfalva [Blaj]","Balffürdő","Balmazújváros","Balogunyom [Ják-Balogunyom]"
,"Balotaszállás","Balsa","Balsai Tisza-part","Bánhalma Halastó","Bánhida"
,"Bánkút","Bánréve","Bánrévei Vízmű","Bar","Baracska"
,"Báránd","Baranovici","Barcs","Barcs felső","Barosstelep"
,"Bashalom","Bátaszék","Baté","Bátonyterenye [Kisterenye]","Battonya"
,"Batyk [Zalabér-Batyk]","Baumgarten","Becehegy","Beclean pe Somes","Bécs [Wien Westbf.]"
,"Becske alsó","Békéscsaba","Bélapátfalva","Bélapátfalvi Cementgyár","Bélatelep"
,"Bélavár","Belecska","Beled","Beleg","Belezna"
,"Belgrád [Beograd]","Beli Manastir","Belsőbáránd","Belsőkamaráspuszta","Belsőperegpuszta"
,"Beltinci","Beograd","Berekfürdő","Berente","Berettyóújfalu"
,"Berkenye","Berlin Hbf","Berlin Ostbhf.","Berlin Südkreuz","Berlin-Spandau"
,"Berlin-Wannsee","Berzence","Bezenye","Biatorbágy","Bicere"
,"Bicsérd","Bicske","Bicske alsó","Biharia Hm.","Biharkeresztes"
,"Biharnagybajom","Biharpüspöki [Episcopia Bihor]","Blaj","Bludenz","Boba"
,"Bocfölde","Bochnia","Bocskaikert","Bodajk","Bodakajtor-Felsőszentiván"
,"Bodolyabér","Bodrogkeresztúr","Bodrogolaszi","Bódvaszilas","Bogárzó"
,"Bohumin","Boldogkőváralja","Boldva","Bolhás","Bóly"
,"Bonyhád [Hidas-Bonyhád]","Bonnya","Borsihalom","Borsodszirák","Borsosberény"
,"Botiz Hm.","Bőcs [Hernádnémeti-Bőcs]","Böhönye","Bölcske","Börgönd"
,"Bősárkány","Bösztör","BP [BUDAPEST*]","Brasov","Brassó [Brasov]"
,"Bratislava hl. st.","Bratislava Nové Mesto","Bratislava-Petrzalka","Breclav","Brest-Central"
,"Brjansk","Brno","Bruck a.d. L.","Brunn a. d. Schneebergbahn","Buchs SG."
,"Bucuresti Nord","Búcsúszentlászló","Budafa","Budafok-Albertfalva","Budafok-Belváros"
,"Budafok-Háros","Budai út","Budaörs","Budapest Airport [Ferihegy]","Budapest Flughafen [Ferihegy]"
,"BUDAPEST*","Budapest-Angyalföld","Budapest-Déli pu.","Budapest-Ferencváros","Budapest-Kelenföld"
,"Budapest-Keleti pu.","Budapest-Nyugati pu.","Budapest-Soroksári út","Budapest-Zugló","Budatétény"
,"Bugac","Bugac felső","Bugacpuszta","Buj","Buj község"
,"Bukarest [Bucuresti Nord]","Burgas","Busag","Büchen","Büdöskútpuszta"
,"Bük","Bükkösd","Campina","Campona [Budatétény]","Caracal"
,"Carei","Cece","Cegléd","Ceglédbercel","Ceglédbercel-Cserő"
,"Ceglédi szállások","Celje","Celldömölk","Center","Center alsó"
,"Ceska Trebova","Cicarlau h.","Cikó","Ciucea","Cluj Napoca"
,"Craiova","Curtici","Czechowice-Dziedzice","Csabacsűd","Csabacsűd felső"
,"Csajág","Csákánydoroszló","Csanádpalota","Csánig","Csány [Hort-Csány]"
,"Csap [Csop]","Csárdaszállás","Csémpuszta","Csengele","Csenger"
,"Csengőd","Csép [Tárkány-Csép]","Csépa","Cserdi-Helesfa","Cserkút [Mecsekalja-Cserkút]"
,"Csermajor [Vitnyéd-Csermajor]","Cserő [Ceglédbercel-Cserő]","Csesznek [Porva-Csesznek]","Csibrák","Csikóstőttős"
,"Csíkszereda [Miercurea Ciuc]","Csincse","Csobád","Csókakő","Csokvaomány"
,"Csomád","Csoma-Szabadi","Csongrád","Csongrád alsó","Csongrádi úti tanyák"
,"Csop","Csopak","Csorna","Csór-Nádasdladány","Csorvás"
,"Csorvás alsó","Csömödér-Páka","Csörög","Csugar","Csurgó"
,"Dabas","Dabronc","Darány","Daránypuszta","Debrecen"
,"Debrecen-Csapókert","Debrecen-Kondoros","Debrecen-Szabadságtelep.","Decin","Decs"
,"Deda","Dédes [Nagyvisnyó-Dédes]","Dej-Calatori","Dejtár","Délegyháza"
,"Déli [Budapest-Déli pu.]","Demecser","Dénesfa","Derecske","Derecske-Vásártér"
,"Dértanya","Dés [Dej-Calatori]","Deszk","Deutschkreutz","Deva"
,"Dévaványa","Devecser","Dinnyés","Diósd [Nagytétény-Diósd]","Diosig Hm."
,"Diósjenő","Divaca","Doboj","Dobova","Dombaytó"
,"Dombostanya","Dombóvár","Dombóvár alsó","Dombrád","Domony [Iklad-Domony]"
,"Donát","Dorog","Döbrököz","Dömösi átkelés","Dömsöd"
,"Dör","Dörgicse [Balatonakali-Dörgicse]","Drassburg","Drégely","Drégelypalánk"
,"Drégelyvár","Dresden Hbf.","Dresden Neustadt","Drezda [Dresden Hbf.]","Dubicsány"
,"Dugo Selo","Dunaalmás","Dunaföldvár","Dunaharaszti","Dunaharaszti alsó"
,"Dunai Finomító","Dunakeszi","Dunakeszi alsó","Dunakeszi-Gyártelep","Dunakömlőd"
,"Dunaújváros","Dunaújváros külső","Dunavarsány","Dúzs","Ebenfurth"
,"Ebes","Ebreichsdorf","Écs","Ecser","Edelény"
,"Edelény alsó","Eger","Egerfarmos","Eger-Felnémet","Egervár"
,"Egervár-Vasboldogasszony","Egyek","Egyházasfalu [Nemeskér-Egyházasfalu]","Egyházasrádóc","Egyházerdő"
,"Eisenstadt","Előhát","Előszállás","Elsterwerda","Emőd"
,"Encs [Forró-Encs]","Enese","Eperjeske alsó","Episcopia Bihor","Eplény"
,"Ercsi","Érd","Érd alsó","Érd felső","Érd-alsó [Érd alsó]"
,"Érd-felső [Érd felső]","Érdliget","Érdliget (Nagytétény-Érdliget) [Nagytétény-Érdliget]","Erdőbénye","Erdőkertes"
,"Erdőkürt [Acsa-Erdőkürt]","Erdőszél","Erdőtelek","Érhát","Érmihályfalva [Valea lui Mihai]"
,"Eszék [Osijek]","Esztár [Pocsaj-Esztár]","Esztergom","Esztergom-Kertváros","Eternitgyár"
,"Fábiánsebestyén","Fácánkert","Fagaras","Fakapu","Farád"
,"Farmos","Fegyvernek-Örményes","Fehérgyarmat","Fehértó felső","Fehérvárcsurgó"
,"Fehring","Feketebézseny","Feldbach","Feldkirch","Felnémet [Eger-Felnémet]"
,"Felsőbogátpuszta","Felsőcebe","Felsőgöd","Felsőjánosfa","Felsőkörtvélyes"
,"Felsőlajos","Felsőméntelek","Felsőmocsolád","Felsőpakony","Felsőrajk"
,"Felsőszentiván [Bodakajtor-Felsőszentiván]","Felsőzsolca","Fenékpuszta","Fényes","Fényeslitke"
,"Fenyveshegy","Ferencváros [Budapest-Ferencváros]","Ferihegy","Fertőboz","Fertőszentmiklós"
,"Fertőszéplak-Fertőd","Filiasi","Fityeház","Fiume [Rijeka]","Fogaras [Fagaras]"
,"Folyás","Fony","Fonyód","Fonyódliget","Forró-Encs"
,"Fót","Fótfürdő","Fótújfalu","Földeák","Fövenyes"
,"Frankfurt (M) Hbf.","Frauenkirchen","Füle","Fülöpszállás","Fürjes"
,"Füzesabony","Füzesbokor","Füzesgyarmat","Füzesgyarmatfürdő","Gacsály"
,"Gádoros","Galambos","Galgaguta","Galgagyörk","Galgahévíz"
,"Galgamácsa","Gárdony","Gátér","Gávavencsellő","Gávavencsellő alsó"
,"Gávavencsellő felső","Gecse-Gyarmat","Gégény","Gelse","Gencsapáti alsó"
,"Gencsapáti felső","General Gh.Avramecsu Hm.","Gevgelija","Gheorghieni","Gilányi"
,"Giurgiu Nord","Gleisdorf","Gniebing","Godisa","Gógánfa"
,"Golop","Gols","Gorzsa","Göd","Gödöllő"
,"Gödöllő Állami telepek","Gömöri [Miskolc-Gömöri]","Gönc","Göncruszka","Görbemajor"
,"Görögszállás","Götzendorf","Gramatneusiedl","Graz","Graz Ost"
,"Grechany","Grünbach am Schneeberg","Grünbach Kohlenwerk","Grünbach Schule","Gutorfölde"
,"Gyál","Gyál felső","Gyarmat [Gecse-Gyarmat]","Gyékényes","Gyenesdiás"
,"Gyergyószentmiklós [Gheorghieni]","Gyoma","Gyomaendrőd [Gyoma]","Gyón","Gyopárosfürdő"
,"Gyökérkút","Gyömöre","Gyömöre-Tét","Gyömrő","Gyöngyfa-Magyarmecske"
,"Gyöngyös","Gyöngyösfalu","Gyöngyöshalász","Gyöngyöshermán","Gyönk [Keszőhidegkút-Gyönk]"
,"Győr","Győrasszonyfa","Győr-Gyárváros","Győrszabadhegy","Győrszemere"
,"Győrszentiván","Győrtelek","Győrtelek alsó","Győrvár","Gyula"
,"Gyulai városerdő","Gyüre","Hajdúbagos","Hajdúböszörmény","Hajdúdorog"
,"Hajdúhadház","Hajdúnánás","Hajdúnánás-Vásártér","Hajdúsámson","Hajdúszentgyörgy"
,"Hajdúszoboszló","Hajdúvid","Hajmáskér","Hajmáskér-Újtelep","Hajnalos"
,"Haláp","Halászlak","Halipuszta","Halmaj","Hamburg Dammtor"
,"Hamburg Hbf.","Hamburg-Altona","Hanságliget","Hanság-Nagyerdő","Haris"
,"Harka","Harkakötöny","Hasznos [Mátraszőlős-Hasznos]","Határcsárda","Hatvan"
,"Hegyeshalom","Hegyfalu","Hejce-Vilmány","Hejőkeresztúr","Hékéd"
,"Helesfa [Cserdi-Helesfa]","Herceghalom","Herend","Herminatanya","Hernád"
,"Hernádnémeti-Bőcs","Hernádszurdok","Hetényegyháza","Hetvehely","Heves"
,"Hevesvezekény","Hévízgyörk","Hidas-Bonyhád","Hidasnémeti","Himberg"
,"Hird [Vasas-Hird]","Hittanya","Hmelniki","Hodász","Hódmezővásárhely"
,"Hódmezővásárhelyi Népkert","Hódmezővásárhely-Ipartelepek","Hodos","Hohenbrugg a. d. Raab","Homok"
,"Horgos","Hort-Csány","Hortobágy","Hortobágyi Halastó","Horvátnádalja"
,"Hosszúberek-Péteri","Hosszúhát","Hosszúhetény","Hosszúpályi","Hőgyész [Szakály-Hőgyész]"
,"Huedin","Hugyag","Hűvösvölgy","Ibrány","Ibrányi temető"
,"Idomeni","Iklad-Domony","Iklad-Domony felső","Iklódbördőce","Ikrény"
,"Ilba h.","Ilia","Ináncs","Inárcs-Kakucs","Innsbruck"
,"Inota","Ipolyszög","Ipolytarnóc","Ipolyvece","Isaszeg"
,"Istvántelek","Ivacs","Iváncsa","Jakabszállás","Jakabszállási tanyák"
,"Ják-Balogunyom","Jákó-Nagybajom","Jánkmajtis","Jánoshalma","Jánosháza"
,"Jánoshida [Jászboldogháza-Jánoshida]","Jánossomorja","Jánosszállás","Jászapáti","Jászárokszállás"
,"Jászberény","Jászboldogháza-Jánoshida","Jászdózsa","Jászfényszaru","Jászkisér"
,"Jászkisér felső","Jászladány","Jászszentlászló","Jennersdorf","Jobbágyi"
,"Jókút [Kúty]","Jósvafő-Aggtelek","Józsa","József Szanatórium","Justhmajor"
,"Kaba","Kádárta","Kajdacs","Kákics","Kakucs [Inárcs-Kakucs]"
,"Kál-Kápolna","Kállósemjén","Kámon","Kapitányság","Kápolnadűlő"
,"Kápolnásnyék","Kapoly","Kaposfő","Kaposfüred","Kaposhomok"
,"Kaposmérő","Kapospula","Kapostüskevár","Kaposújlak","Kaposvár"
,"Kaposvári Textilművek [Kapostüskevár]","Kaposvár-Közvágóhíd [Kaposszentjakab]","Kaposszekcső","Kaposszentjakab","Kapronca [Koprivnica]"
,"Káptalanfüred","Kapuvár","Karácsond","Karád","Karakószörcsök"
,"Kárász-Köblény","Kárászpuszta [Okorág-Kárászpuszta]","Karcag","Karcag Ipartelep","Karcag-Vásártér"
,"Kardoskút","Karlovac","Karlsruhe Hbf.","Károlyháza [Kimle]","Karpati"
,"Kaskantyú","Kaspichan","Kassa [Kosice]","Katonatelep","Katowice"
,"Katzelsdorf","Kazatin Pass.","Kazincbarcika","Kazincbarcika alsó","Kecskéd alsó"
,"Kecskemét","Kecskemét alsó","Kecskemét KK","Kecskemét-Máriaváros","Kehl"
,"Kék","Kelebia","Kelenföld [Budapest-Kelenföld]","Keleti [Budapest-Keleti pu.]","Kemecse"
,"Kemendollár","Kemenesmihályfa","Kemenespálfa","Kenderes","Kengyel"
,"Kerekdomb","Kerta","Kertekalja [Vecsés-Kertekalja]","Keszőhidegkút-Gyönk","Keszthely"
,"Kétegyháza","Kétérköz","Kéthely","Kétpó","Kettőshalom"
,"Kétútköz","Kiev","Kilimán","Kimle","Királd"
,"Királyegyháza-Rigópuszta","Királyhida [Bruck a.d. L.]","Kisapáti [Nemesgulács-Kisapáti]","Kisbárapáti","Kisbér"
,"Kisbócsa","Kiscsákó","Kiscséripuszta","Kisdobsza","Kisfái"
,"Kisfástanya","Kishajmás [Szatina-Kishajmás]","Kiskapud","Kiskorpád","Kisköre"
,"Kisköre-Tiszahíd","Kiskőrös","Kiskőrös KK","Kiskőrösi út","Kiskundorozsma"
,"Kiskunfélegyháza","Kiskunhalas","Kiskunlacháza","Kiskunmajsa","Kiskunmajsa KK"
,"Kislőd [Városlőd-Kislőd]","Kismargita","Kismarja","Kismaros","Kismindszenti út"
,"Kisnémedi","Kispest","Kistelek","Kisteleki szőlők","Kisterenye"
,"Kisterenye-Bányatelep","Kistokaj","Kistótfalu","Kistőke","Kisújszállás"
,"Kisvác","Kisvárda","Kisvárda-Hármasút","Kisvarsány","Kiszombor"
,"Kiszombor megálló","Kisszállás","Kisszekeres","Kisszénás","Kitérőgyár"
,"Kittsee","Klábertelep","Kledering","Klotildliget","Knin"
,"Kocsistanya","Kocsord","Kocsord alsó","Kolin","Kolontár"
,"Kolozsvár [Cluj Napoca]","Komádi","Komárom","Komjáti","Komló"
,"Komlósd [Péterhida-Komlósd]","Komoró","Kondoros","Konotop","Kóny"
,"Kónya","Konyár","Konyári Sóstófürdő","Kónyaszék","Kópháza"
,"Koprivnica","Korlát-Vizsoly","Kórógyszentgyörgy","Kosice","Kótaj"
,"Kótpuszta","Kőbánya alsó","Kőbánya felső","Kőbánya-Kispest","Köblény [Kárász-Köblény]"
,"Kölesd-Alsótengelic","Köncsögpuszta","Körmend","Környe","Kőröshegy [Szántód-Kőröshegy]"
,"Körösladány","Körösnagyharsány","Körösújfalu","Körösszakál","Kőszeg"
,"Kőszegfalva","Kötegyán","Köveskál [Zánka-Köveskál]","Középmező","Középrigóc"
,"Központi Főmajor","Krakkó [Kraków]","Kraków","Krakow Plaszow","Krizevci"
,"Kroisbach-Zöbing","Kulata","Kulcs","Kunfehértó","Kungyalu"
,"Kunhegyes","Kunmadaras","Kunszállás","Kunszentmárton","Kunszentmiklós-Tass"
,"Kurd","Kutas","Kútitanya","Kútvölgy","Kúty"
,"Külsővat","Kürtös [Curtici]","Kysak","Lábatlan","Lajosmizse"
,"Lajosmizse alsó","Lakitelek","Lanzendorf Rannersdorf","Lasko","Lassnitzhöhe"
,"Lassnitzthal","Lavochne","Leányvár","Lébény-Mosonszentmiklós","Lemberg [Lvov]"
,"Lenartovce","Lengyeltóti (Buzsák)","Lenti","Lentiszombathely","Lepsény"
,"Lesencetomaj","Létavértes","Levél","Levelek-Magy","Ligettanya"
,"Linz Hbf.","Lipany","Litija","Litke","Ljubljana"
,"Ljutomer Mesto","Loipersbach-Schattendorf","Lödersdorf","Lőkösháza","Lőrinci"
,"Lőtér","Lövő","Ludányhalászi","Ludas","Ludastó"
,"Ludus","Ludwigslust","Lukácsháza","Lukácsháza alsó","Lukow"
,"Lvov","Macs","Mád","Maglód","Maglódi nyaraló"
,"Mágocs-Alsómocsolád","Magy [Levelek-Magy]","Magyarbánhegyes","Magyarbóly","Magyarcsanád"
,"Magyarhertelend","Magyarkeresztúr-Zsebeháza","Magyarkút","Magyarkút-Verőce","Magyarmecske [Gyöngyfa-Magyarmecske]"
,"Magyarnándor","Magyarsor","Magyarszék","Magyarszerdahely","Maklár"
,"Makó","Makó-Újváros","Makó-Újvásártér","Mándok","Marcali"
,"Máriabesnyő","Máriapócs","Máriaudvar","Márkó","Márok"
,"Marosvásárhely [Targu Mures]","Mártély","Martfű","Martonvásár","Marz-Rorbach"
,"Mátéházapuszta","Mátészalka","Matkó alsó","Mátraszőlős-Hasznos","Mátraverebély"
,"Mátravidéki Erőmű","Mattersburg","Mattersburg Nord","Máza-Szászvár","Mecsekalja-Cserkút"
,"Mecsekjánosi","Mecsekpölöske","Medgyesegyháza","Medias","Mediesu Aurit"
,"Meggyespele","Méhkerék","Mélykút","Mende","Ménfőcsanak"
,"Ménfőcsanak felső","Méntelek","Méra","Mernye","Mesztegnyő"
,"Mezőberény","Mezőfalva","Mezőhegyes","Mezőkeresztes-Mezőnyárád","Mezőkovácsháza"
,"Mezőkovácsháza felső","Mezőkövesd","Mezőkövesd felső","Mezőlak","Mezőnyárád [Mezőkeresztes-Mezőnyárád]"
,"Mezőpeterd","Mezőtárkány","Mezőtúr","Mezőzombor","Miercurea Ciuc"
,"Mihályháza","Miklóstelep","Mindszent","Minsk Passz.","Miskolc [Miskolc-Tiszai pu.]"
,"MISKOLC*","Miskolc-Gömöri","Miskolc-Tiszai pu.","Mogersdorf","Moha"
,"Mohács","Moha-Rakodó","Mohora","Molvány","Monfalcone"
,"Monor","Monorierdő","Mónosbél","Monostorpályi","Mór"
,"Mórágy","Mórágy-Alsónána","Móricgát","Moskva Biel.","Moskva Kievskaja"
,"Mosonmagyaróvár","Mosonszentmiklós [Lébény-Mosonszentmiklós]","Mosonszolnok","Mőcsény","Mönchhof-Halbturn"
,"Mözs [Tolna-Mözs]","Munkacsevo","Murakeresztúr","Murony","Murska Sobota"
,"Muszyna","Müllendorf","München Hbf.","München Ost","Nádasd"
,"Nádasdladány [Csór-Nádasdladány]","Nagyatád","Nagybajom [Jákó-Nagybajom]","Nagybátony","Nagyberény [Som-Nagyberény]"
,"Nagyberki","Nagybugac","Nagycenk","Nagycsécs","Nagycsere"
,"Nagydobos","Nagydorog","Nagyecsed","Nagyér","Nagyerdő [Hanság-Nagyerdő]"
,"Nagyhalász","Nagyhalászi Kendergyár","Nagyhát","Nagyigmánd-Bábolna","Nagykálló"
,"Nagykanizsa","Nagykapornak","Nagykarácsony","Nagykarácsony felső","Nagykároly [Carei]"
,"Nagykáta","Nagykereki","Nagykőrös","Nagylak","Nagylaki Kendergyár"
,"Nagylapos","Nagylók","Nagymajor","Nagymányok","Nagymaros"
,"Nagymaros-Visegrád","Nagynyárád","Nagynyír","Nagyoroszi","Nagypeterd"
,"Nagyrákos","Nagyrécse","Nagysimonyi","Nagyszalonta [Salonta]","Nagyszeben [Sibiu]"
,"Nagyszekeres","Nagyszénás","Nagyszentjános","Nagytanya","Nagytétény"
,"Nagytétény-Diósd","Nagytétény-Érdliget","Nagytőke","Nagyút","Nagyvárad [Oradea]"
,"Nagyvisnyó-Dédes","Napkor","Nekézseny","Nemesgulács-Kisapáti","Nemeske"
,"Nemeskér-Egyházasfalu","Nemeskeresztúr","Nemeskocs","Neszehíd","Neszmély"
,"Neudörfl","Neufeld a.d. L.","Neusiedl am See","Nezsider [Neusiedl am See]","Nickelsdorf"
,"Nis","Nógrád","Nógrádkövesd","Nógrádszakál","Novajidrány"
,"Nove Zamky","Novi Beograd","Novi Sad","Nowy Sacz","Nyárjas"
,"Nyárlőrinc","Nyárlőrinc alsó","Nyárlőrinci szőlők","Nyársapát","Nyékládháza"
,"Nyergesújfalu","Nyergesújfalu felső","Nyírábrány","Nyíradony","Nyírbátor"
,"Nyírbogát","Nyírbogdány","Nyírcsaholy","Nyírcsászári","Nyíregyháza"
,"Nyíregyháza külső","Nyíregyháza NyK.","Nyíregyháza-Vásártér","Nyírgelse","Nyírlak"
,"Nyírmada","Nyírmeggyes","Nyírmihálydi","Nyírszőlős","Nyírtelek"
,"Nyugati [Budapest-Nyugati pu.]","Nyúl","Óbög","Óbuda","Ócsa"
,"Ócsai szőlők","Odoreu hc.","Ófehértó","Ogulin","Ohat-Pusztakócs"
,"Okány","Okorág-Kárászpuszta","Olaszliszka-Tolcsva","Olomouc hl. n.","Onga"
,"Ongaújfalu","Ópályi","Oradea","Orgovány","Ormoz"
,"Oros","Orosháza","Orosháza felső","Orosháza-Üveggyár","Orosházi tanyák"
,"Oroszlány","Orsa","Ortaháza","Osijek","Ostffyasszonyfa"
,"Ostrava hl. n.","Ostrava-Svinov","Oswiecim","Osztopán","Ózd"
,"Ózd alsó","Őcsény","Ököritófülpös","Ölbő-Alsószeleste","Őrbottyán"
,"Öreglak","Őrhalom","Őriszentpéter","Örkény","Örményes [Fegyvernek-Örményes]"
,"Őrtilos","Örvényes","Öskü","Őszeszék","Öttevény"
,"Ötvöskónyi","Pacsa [Zalaszentmihály-Pacsa]","Pácsony","Páhi","Páka [Csömödér-Páka]"
,"Pakod","Paks","Paks-Dunapart","Palánk [Szekszárd-Palánk]","Palic"
,"Páli-Vadosfa","Palkonya","Pálmajor","Palocsa [Plavec]","Pamhagen"
,"Pamuk","Pankasz","Pannonhalma","Pápa","Pardubice"
,"Parndorf","Parndorf Ort","Paszab","Pásztó","Pátroha"
,"Pázmáneum","Pécel","Pécs","Pécs felső","Pécsbánya-Rendező"
,"Pécs-Gyárváros","Pécs-Külváros","Pécsudvard","Pécsújhegy","Pécsvárad"
,"Pécs-Vasas","Pélmonostor [Beli Manastir]","Penyige","Pereszteg","Perkovic"
,"Perkupa","Pernik","Pest [BUDAPEST*]","Pesterzsébet","Pestszentimre"
,"Pestszentimre felső","Pestszentlőrinc","Péterhida-Komlósd","Péteri [Hosszúberek-Péteri]","Pétfürdő"
,"Petőfiszállás","Petőfiszállási tanyák","Petőfiváros","Petőháza","Petrosani"
,"Pettend","Pfenningbach","Pforzheim","Pilawa","Pilis"
,"Piliscsaba","Piliscsév","Pilisjászfalu","Pilisvörösvár","Pincehely"
,"Pinnye","Piroska","Pirtó","Pirtói szőlők","Piski [Simeria]"
,"Piszke","Pitvaros","Piwniczna Zdroj","Plavec","Pleven"
,"Ploiesti Vest","Pocsaj-Esztár","Podgorica","Pogonyipuszta","Pókaszepetk"
,"Polgár","Polgárdi","Polgárdi-Ipartelepek","Polgárdi-Tekerespuszta","Pomogy [Pamhagen]"
,"Porcsalma-Tyukod","Poroszló","Porpác","Porrogszentkirály","Portelek"
,"Porva-Csesznek","Pósfa","Postojna","Pozsony [Bratislava hl. st.]","Pörböly"
,"Pötréte","Prága [Praha hl. n.]","Pragersko","Prague [Praha hl. n.]","Praha hl. n."
,"Praha Holesovice","Predeal","Prerov","Presevo","Presov"
,"Promachon","Ptuj","Puchberg am Schneeberg","Pusztabánréve","Pusztaberény"
,"Pusztakettős","Pusztakócs [Ohat-Pusztakócs]","Pusztamonostor","Pusztapó","Pusztaszabolcs"
,"Pusztaszentistván","Pusztatemplom","Putnok","Püspökhatvan","Püspökladány"
,"Püspökladány-Vásártér","Püspökmolnári","Raaba","Rábapatona","Rábatamási"
,"Rácalmás","Rádiháza","Radna","Rajka","Rakamaz"
,"Rákóczitanya","Rákos","Rákoscsaba","Rákoscsaba-Újtelep","Rákoshegy"
,"Rákoskert","Rákosliget","Rákospalota-Kertváros","Rákospalota-Újpest","Rákosrendező"
,"Raposka","Ráróspuszta","Rátka","Rátót","Ravazd"
,"Razboieni","Rédics","Reghin","Regöly","Reje"
,"Répáspuszta","Répcelak","Rétszilas","Rétszilas alsó","Révfülöp"
,"Rigács","Rigópuszta [Királyegyháza-Rigópuszta]","Rijeka","Rohod [Vaja-Rohod]","Rohr Haltestelle"
,"Rosenheim","Rosiori Nord","Rothengrub","Rozsály","Röszke"
,"Rudnaykert","Ruse","Rytro","S. Dona di Piave","Sabinov"
,"Sabisa hc.","Sacueni Bihor","Sajóecseg","Sajókaza","Sajókeresztúr"
,"Sajónémeti","Sajószentpéter","Sajószentpéter-Piactér","Sajószöged","Salgótarján"
,"Salgótarján külső","Salköveskút-Vassurány","Salomvár [Zalacséb-Salomvár]","Salonta","Salzburg Hbf."
,"Sanislau Hm.","Sáp","Sarajevo","Sáránd","Sarasdorf"
,"Saratel","Sárbogárd","Sáregres","Sargans","Sárhida"
,"Sarkad","Sarkadi Cukorgyár","Sarkadkeresztúr","Sárkeresztúr","Sárkeresztúr [Aba-Sárkeresztúr]"
,"Sárosd","Sároskőszeg [Kysak]","Sárospatak","Sárpentele","Sárpilis-Várdomb"
,"Sárrétudvari","Sárszentágota","Sárszentmihály","Sárvár","Sásd"
,"Sáta","Sátoraljaújhely","Satu Mare","Satu Mare Sud","Sávoly"
,"Segesd","Segesvár [Sighisoara]","Seini","Sellye","Selymes"
,"Selyp","Sepsiszentgyörgy [Sfantu Gheorghe]","Seregélyes","Seregélyes-Szőlőhegy","Sezana"
,"Sfantu Gheorghe","Sibiu","Sighisoara","Silindru Hm.","Simeria"
,"Simontornya","Sinaia","Siófok","Siójut","Sióvölgy"
,"Sirató","Skatarske","Skole","Skopje","Slavonski Samac"
,"Smolensk","Sofia","Soltszentimre","Soltvadkert","Soltvadkerti út"
,"Solymár","Somlóvásárhely","Som-Nagyberény","Somodor","Somogyaszaló"
,"Somogyjád","Somogymeggyes","Somogyszentpál","Somogyszentpál felső","Somogyszob"
,"Somogyudvarhely","Somogyvár","Somoskőújfalu","Sopron","Sopronkövesd"
,"Sopronnémeti [Szil-Sopronnémeti]","Sorkifalud","Soroksár","Sóstó","Sóstógyógyfürdő"
,"Sóstóhegy","Split","St. Andre am Zicksee","St. Petersburg Viteb","St. Pölten"
,"St. Valentin","Stara Pazova","Stary Sacz","Strasbourg","Strizivojna-Vrpolje"
,"Stroze","Stryj","Studenzen-Fladnitz","Sturovo","Stuttgart Hbf."
,"Subotica","Suhinici","Sumony","Sülysáp","Sümeg"
,"Sümegi Bazaltbánya","Süttő","Süttő felső","Svaliava","Szabadbattyán"
,"Szabadegyháza","Szabadifürdő","Szabadisóstó","Szabadka [Subotica]","Szabadkígyós"
,"Szabadságliget","Szabadszállás","Szajol","Szakály-Hőgyész","Szalatnak"
,"Szalonna","Szank","Szanki tanyák","Szántód-Kőröshegy","Szár"
,"Szarajevó [Sarajevo]","Szárazd","Szárazrét","Szárföld","Szárliget"
,"Szarvas","Szarvaskő","Szászberek","Szászvár","Szatina-Kishajmás"
,"Szatymaz","Százhalombatta","Széchenyihegy","Szécsény","Szedres"
,"Szeged","SZEGED*","Szeged-Rókus","Szeghalom","Szegi"
,"Szegvár","Székesfehérvár","Székesfehérvár-Repülőtér","Székkutas","Szekszárd"
,"Szekszárd-Palánk","Szelevény","Szellőhát","Szemeretelep","Szendrő"
,"Szendrő felső","Szendrőlád","Szenta","Szentannapuszta","Szentdénes"
,"Szentes","Szentetornya","Szentgál","Szentgotthárd","Szentléránt"
,"Szentlőrinc","Szentmártonkáta","Szepezdfürdő","Szerecseny","Szerencs"
,"Szerep","Szigetvár","Szigliget [Badacsonytördemic-Szigliget]","Szihalom","Szikáncs"
,"Szikra","Szikszó","Szikszó-Vásártér","Szil-Sopronnémeti","Szilvásvárad"
,"Szilvásvárad-Szalajkavölgy","Szirmabesenyő","Szob","Szob alsó","Szófia [Sofia]"
,"Szokolya","Szolnok","Szombathely","Szombathely-Szőlős","Szorgalmatos"
,"Szőce [Zalaháshágy-Szőce]","Sződliget [Sződ-Sződliget]","Sződ-Sződliget","Szőkéd","Szőlőstelep"
,"Szőny","Szőny-Déli","Szőreg","Szurdokpüspöki","Szügy"
,"Tab","Tabdi","Táborfalva","Tajó","Takern-St. Margareten"
,"Taksony","Taktaharkány","Taktaszada","Tállya","Tamásipuszta"
,"Tápiógyörgye","Tápiószecső","Tápiószele","Tápiószentmárton","Tapolca"
,"Tar","Tarcal","Tardosi Kőbányák","Targu Jiu","Targu Mures"
,"Tarjánpuszta","Tárkány-Csép","Tarnaszentmiklós","Tárnok","Tarnow"
,"Tass [Kunszentmiklós-Tass]","Taszár","Tát","Tata","Tatabánya"
,"Tatárvár","Tedej","Téglás","Teius","Tekerespuszta [Polgárdi-Tekerespuszta]"
,"Telekgerendás","Temesvár [Timisoara Nord]","Tengelic","Terespol","Ternopol"
,"Tét [Gyömöre-Tét]","Thessaloniki","Tiborszállás","Tihany [Balatonfüred]","Timisoara Nord"
,"Tiszaalpár","Tiszaalpár alsó","Tiszaalpár felső","Tiszabercel","Tiszabercel-Vásártér"
,"Tiszabezdéd","Tiszacsege","Tiszadada","Tiszadob","Tiszaeszlár"
,"Tiszaföldvár","Tiszafüred","Tiszafüred-Gyártelep","Tiszajenő alsó","Tiszajenő-Vezseny"
,"Tiszakécske","Tiszalök","Tiszalöki Vízművek","Tiszalúc","Tiszapalkonya-Erőmű"
,"Tiszasas","Tiszaszentimre","Tiszaszőlős","Tiszatelek","Tiszatenyő"
,"Tiszaug","Tiszaug-Tiszahídfő","Tiszaújváros","Tiszavárkony","Tiszavasvári"
,"Tisztavíz","Tócóvölgy","Tófej","Tófürdő","Tokaj"
,"Tokod","Tolcsva [Olaszliszka-Tolcsva]","Tolna-Mözs","Tolnanémedi","Tompa"
,"Tompapuszta","Toplita","Toponár","Tormásliget","Tornanádaska"
,"Tornyospálca","Tószeg","Tóth tanya","Tótkomlós","Tóvároskert"
,"Törökbálint","Törökfái","Törökszentmiklós","Tőserdő","Trautmannsdorf/L."
,"Trbovlje","Trzebinia","Tunyogmatolcs","Tunyogmatolcs alsó","Tura"
,"Tuzsér","Türje","Tüskevár","Tyukod [Porcsalma-Tyukod]","Újbög"
,"Újdombrád","Újfehértó","Újkenéz","Újkér","Újkótaj"
,"Újpest","Újszász","Újszeged","Újszentmargita","Újtikos"
,"Újudvar","Újváros","Újvenyim","Újvidék [Novi Sad]","Ukk"
,"Ulm Hbf.","Unterhöflein","Úrihegy","Usti n. Orlici","Usti nad Labem"
,"Uzsa","Uzsabánya alsó","Üllő","Üröm","Vác"
,"Vác-Alsóváros","Váchartyán","Váckisújfalu","Vácrátót","Vadna"
,"Vadosfa [Páli-Vadosfa]","Vaja-Rohod","Vajsma","Vajta","Valea lui Mihai"
,"Vámoscsalád","Vámosgyörk","Vámospércs","Váralja","Várda"
,"Várdomb [Sárpilis-Várdomb]","Várhegyalja","Varna","Városföld","Városi park"
,"Városlőd","Városlőd-Kislőd","Várpalota","Vásárosdombó","Vásárosnamény"
,"Vásárosnamény külső","Vasas-Hird","Vasboldogasszony [Egervár-Vasboldogasszony]","Vasegerszeg","Vassurány [Salköveskút-Vassurány]"
,"Vasútmúzeum","Vasvár","Vaszar","Vecsés","Vecsés-Kertekalja"
,"Végegyháza","Végegyháza alsó","Velence","Velencefürdő","Venezia Mestre"
,"Venezia S. L.","Vép","Veresegyház","Verőce","Verőce [Magyarkút-Verőce]"
,"Vértesszőlős","Veszkény","Veszprém","Veszprémvarsány","Vésztő"
,"Vezseny [Tiszajenő-Vezseny]","Vica","Vicziántelep","Videle","Vienna [Wien Westbf.]"
,"Világoshegy","Villa Opicina","Villány","Villánykövesd","Vilmány [Hejce-Vilmány]"
,"Vilmaszállás","Vinár","Vinnica","Vintu de Jos","Vinye"
,"Virányos","Visegrád [Nagymaros-Visegrád]","Vitka","Vitnyéd-Csermajor","Vízvár"
,"Vizslás","Vizsoly [Korlát-Vizsoly]","Vokány","Volovec","Vonyarcvashegy"
,"Vörs","Vrbas","Vrbovec","Wallern im Burgenland","Warszawa Centralna"
,"Warszawa Wschodnia","Weiden am See","Wels","WIEN [Wien Westbf.]","Wien Südbf. Bstg.11-19"
,"Wien Südbf. Bstg.1-9","Wien Westbf.","WIEN*","Wiener Neustadt","Wien-Hütteldorf"
,"Wien-Meidling","Wiesen-Siegless","Wilfleinsdorf","Willendorf","Winzendorf"
,"Wittenberge","Wulkaprodersdorf","Zagorje","Zágráb [Zagreb Gl. Kol.]","Zagreb Gl. Kol."
,"Zagyvapálfalva","Zagyvarékas","Zagyvaszántó [Apc-Zagyvaszántó]","Záhony","Zajta"
,"Zákány","Zalabér-Batyk","Zalacséb-Salomvár","Zalaegerszeg","Zalaegerszeg-Ola"
,"Zalagyömörő","Zalaháshágy-Szőce","Zalakomár","Zalalövő","Zalapatakalja"
,"Zalaszentgyörgy","Zalaszentiván","Zalaszentjakab","Zalaszentlőrinc","Zalaszentmihály-Pacsa"
,"Zamárdi","Zamárdi felső","Zamárdi-felső [Zamárdi felső]","Zánka [Zánka-Köveskál]","Zánkafürdő"
,"Zánka-Köveskál","Zebegény","Zebrzydowice","Zegiestow Zdroj","Zelemér"
,"Zenica","Zichyújfalu","Zidani Most","Ziliz","Zirc"
,"Zrínyitelep","Zugló [Budapest-Zugló]","Zurndorf","Zürich Hb.","Zsebeháza [Magyarkeresztúr-Zsebeháza]"
,"Zsujta"];

CmdUtils.CreateCommand({
	names: ["elvira"],
	description: "Check Elvira timetable",
	help: "elvira (from) (to) (as student) (at [date])",
	icon: "http://elvira.mav-start.hu/xslms/res/favicon.ico",
	author: {name: "Gazs", email: "gazs@bergengocia.net"},
	license: "GPL",
	
	arguments: [
		{
			role: "source",
			nountype: mav,
			label: "origin",
		},
		{
			role: "goal",
			nountype: mav,
			label: "destination",
		},
		{
			role: "alias",
			nountype: ["student"],
			label: "reduction", //izé, kedvezmény.
		},
		{
			role: "time",
			nountype: noun_type_date,
			label: "date of departure",
		},
	],
	preview: function (pb, arguments) {
		$.ajaxSetup({
		    'beforeSend' : function(xhr) {
	            xhr.overrideMimeType('text/html; charset=ISO-8859-2');
	    	    },
		});
		var source = escape(Utils.convertFromUnicode("ISO-8859-2", arguments.source.text));
		var goal = escape(Utils.convertFromUnicode("ISO-8859-2", arguments.goal.text));
		var datum = arguments.time.data.toString("yy.MM.dd");
		if (source.length >0 && goal.length >0) {
				switch (arguments.alias.text) {
					case "student":
						var u=1;
						break;
					default:
						var u=29;
						break;
				}
			jQuery.get('http://elvira.mav-start.hu/elvira.dll/xslms/uf?mikor=-1&i='+ source +'&e=' + goal + '&sk=5&d='+ datum +'&u=' + u, null, function (page) {
				var elviracska ="";
				$("div#timetable > table > tbody > tr > td.noprint > div.jsubmit > form.jsubmit > input[type=submit]", page).each(function(i) {
				        var honnan = $(this).parent().parent().parent().siblings().filter(".l:eq(0)").text().trim();
				        var indul = $(this).parent().parent().parent().siblings().filter(".l:eq(1)").text().trim();
				        var erkezik = $(this).parent().parent().parent().siblings().filter(".l:eq(2)").text().trim();
				        var masodosztalyar = $(this).parent().parent().parent().siblings().filter(".r:eq(2)").text().trim();
				        var rendeleslink = "https://jegyvasarlas.mav-start.hu/eTicketV2/Jegykivalasztas?" + $(this).parent().serialize();
					elviracska += '<li><a href="'+ rendeleslink +'">'+honnan+' - '+indul+'-'+erkezik+' : '+masodosztalyar+'</a></li>';
				})
				pb.innerHTML = elviracska;
			})
		}
		return;
	},
	execute: function( arguments ) {
		var datum = arguments.time.data.toString("yy.MM.dd");
		var source = escape(Utils.convertFromUnicode("ISO-8859-2", arguments.source.text));
		var goal = escape(Utils.convertFromUnicode("ISO-8859-2", arguments.goal.text));
		Utils.openUrlInBrowser("http://elvira.mav-start.hu/elvira.dll/xslms/uf?mikor=-1&i="+ source +"&e=" + goal + "&d=" + datum + "&u=1");
		return;
	}
})